name: Lint
on: ['push']
#  push:
#    paths:
#    - 'charts/**'


jobs:
  lint-test:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Add Chart Repos
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Run chart-testing (lint)
      run: ct lint --all --validate-maintainers=false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v8.9

    - name: List all modified files
      run: |
        export CHANGED_CHART=""
        for file in ${steps.changed-files.outputs.all_modified_files}; do
          if [[ $file == *"charts"* ]]; then
            chart=`echo $file | sed 's/charts\///g' | sed 's/\/.*//g'`
            # If chart is not found in changed chart add it
            if ! [[ $CHANGED_CHART =~ $chart  ]];then
              export CHANGED_CHART="$CHANGED_CHART $chart"
            fi
          fi
        done
        # Trim leading space
        export CHANGED_CHART=$(echo $CHANGED_CHART | sed 's/^ *//g')
        echo "::set-output name=changed_charts::$CHANGED_CHART"

  release-charts:
    runs-on: 'ubuntu-latest'
    needs: lint-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello World
      run: echo "Hello world!"
